#!/usr/bin/perl -w  
########################################################################################################################################################################################
## use hash to visit the phrases; calculate the probability                                                                                                                                                                                 #####
########################################################################################################################################################################################

# # sorted_left-print

open FR,"<:encoding(utf8)","sorted_left-print"; ## put the french co-occurance file

open TEST_FR,">:encoding(utf8)","sorted_left-print_TEST_hash" or die "can't open fun_Spearman_Coe_Rank_fr_en_eur_bleu.txt\n";

	$str_tem="";
	@arry_tem=();

	while($str_tem=<FR>)    # it looks like '5 ||| french'
		{
			chomp($str_tem);
			@arry_tem=split(/\s+\|\|\|\s+/, $str_tem);
			$FR_coocur_hash{$arry_tem[1]}= $arry_tem[0];   # key is the 'french', value is the num

			$str_tem="";
			@arry_tem=();

		}


	foreach $key (sort keys %FR_coocur_hash) #### put the keys into order then print out key-value, check the fr hash
		{
  			print TEST_FR 'the co-ccur of fr :'. "$key => $FR_coocur_hash{$key}\n";
 		}



close FR;

close TEST_FR;





open FR_EN,"<:encoding(utf8)","sorted_with_counts-clear-2"; ## put the french-en co-occurance file. 'co-ocur ||| fr ||| en'
	$str_tem2="";
	@arry_tem2=();

	while($str_tem2=<FR_EN>)    # 'co-ocur ||| fr ||| en'
		{
			chomp($str_tem2);
			@arry_tem2=split(/\s+\|\|\|\s+/, $str_tem2);
			$FR_EN_coocur_hash{$arry_tem2[1].' ||| '.$arry_tem2[2]}= $arry_tem2[0];   # key is the 'french ||| english', value is the num

			$str_tem2="";
			@arry_tem2=();

		}

open TEST_FR_EN,">:encoding(utf8)","sorted_with_counts-clear-2_TEST_hash" or die "can't open fun_Spearman_Coe_Rank_fr_en_eur_bleu.txt\n";

	foreach $key (sort keys %FR_EN_coocur_hash) #### put the keys into order then print out key-value, check the fr-en hash
		{
  			print TEST_FR_EN 'the co-ccur of fr_en :'. "$key => $FR_EN_coocur_hash{$key}\n";
 		}
close TEST_FR_EN;

close FR_EN;




open OUTPUT,">:encoding(utf8)","FR_EN_trans_Prob" or die "can't open fr-en-trans-prob\n";
	@arry_tem3=();
	$prob_fr_en=0;

	foreach $key (%FR_EN_coocur_hash)    #### go through two Hash, calculate translation probability fr-to-en 
	 	{
	 		@arry_tem3=split(/\s+\|\|\|\s+/, $key);
	 		if(exists $FR_coocur_hash{$arry_tem3[0]})
	 			{
					$prob_fr_en= $FR_EN_coocur_hash{$key}/$FR_coocur_hash{$arry_tem3[0]};					
	 				print OUTPUT "$key ||| $prob_fr_en \n";
	 				$prob_fr_en=0;
	 			}
	 	}
close OUTPUT;


